# Generated by Django 4.0.4 on 2022-04-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', '-created_at']},
        ),
    ]
